---
title: "Translocation Examples"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
library(GENOVA)
library(grid)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
exps <- load_experiments(sample_subset = c("P04_PB", "P04_LM"), 
                         resolution = 1e6, balancing = FALSE)
exps <- sync_indices(exps)
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

### P04

```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr1", "chr3", "chr8", "chr10", "chr17", "chr18", "chrX")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P04_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P04_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)
df[, cis := bins$V1[row] == bins$V1[col]]

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]
brks$V1[-1] <- gsub("chr", "", brks$V1[-1])

size <- 5


g <- ggplot(df, aes(col, row, fill = value)) +
  geom_raster(data = ~ subset(.x, cis),
              aes(fill = value)) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 2000),
    oob = oob_squish
  ) +
  ggnewscale::new_scale_fill() +
  geom_raster(data = ~ subset(.x, !cis),
              aes(fill = value)) +
  geom_hline(yintercept = brks$min[-1]) +
  geom_vline(xintercept = brks$min[-1]) +
  myplotdefaults::scale_fill_ice(
    limits = c(0, 1000),
    oob = oob_squish,
    breaks = c(0, 500, 1000)
  ) +
  annotate(
    "label", x = c(Inf, -Inf), y = c(-Inf, Inf),
    label = c("P04 PB" , "P04 LM"), hjust = c(1, 0), vjust = c(1, 0),
    label.padding = unit(2.25, "pt"), label.size = NA,
    fill = NA
  ) +
  guides(
    x.sec = ggh4x::guide_axis_scalebar(
      size = 50, label = "50 Mb"
    ),
    fill = gguidance::guide_colourbar_cap(
      cap_position = "upper",
      barheight = unit(5.5, "pt"),
      barwidth = unit((size - 0.1672)/2, "cm"),
      order = 2,
      title.position = "top"
    ),
    fill_new = gguidance::guide_colourbar_cap(
      cap_position = "upper", available_aes = "fill_new",
      barheight = unit(5.5, "pt"),
      barwidth = unit(size - 0.1672, "cm"),
      title = "Contacts",
      title.position = "top",
      order = 1
    )
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0),
    breaks = brks$mid,
    labels = brks$V1,
    name   = NULL
  ) +
  scale_x_continuous(
    expand = c(0, 0),
    breaks = brks$mid,
    labels = brks$V1,
    name   = NULL
  ) +
  ggh4x::force_panelsizes(
    rows = unit(size, "cm"),
    cols = unit(size, "cm")
  ) +
  theme(
    axis.text.y.left = element_text(angle = 90, hjust = 0.5),
    aspect.ratio = 1,
    legend.position = "bottom",
    legend.box = "vertical",
    legend.box.just = "left",
    legend.text = element_text(hjust = 0.5)
  )

save_svg("Fig_Translocation_Example1", g)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr3", "chr10", "chr18", "chrX")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P04_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P04_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]

ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```


### P03

```{r}
exps <- load_experiments(sample_subset = c("P03_PB", "P03_LM"), 
                         resolution = 5e5, balancing = FALSE)
exps <- sync_indices(exps)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr1", "chr10", "chr16", "chrX")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P03_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P03_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr4", "chr5", "chr6","chr14")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P03_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P03_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```

```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr10", "chr12", "chrX")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P03_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P03_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), 
             by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr20", "chr12", "chr11", "chr14")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P03_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P03_LM$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), 
             by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```

### P02

```{r}
exps <- load_experiments(sample_subset = c("P02_HB", "P02_PB"), 
                         resolution = 1e6, balancing = FALSE)
exps <- sync_indices(exps)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr11", "chr13", "chr20", "chr6")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P02_HB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P02_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)
df[, cis := bins$V1[row] == bins$V1[col]]

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]
brks$V1[-1] <- gsub("chr", "", brks$V1[-1])

size <- 5


g <- ggplot(df, aes(col, row, fill = value)) +
  geom_raster(data = ~ subset(.x, cis),
              aes(fill = value)) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 2000),
    oob = oob_squish
  ) +
  ggnewscale::new_scale_fill() +
  geom_raster(data = ~ subset(.x, !cis),
              aes(fill = value)) +
  geom_hline(yintercept = brks$min[-1]) +
  geom_vline(xintercept = brks$min[-1]) +
  myplotdefaults::scale_fill_ice(
    limits = c(0, 1000),
    oob = oob_squish,
    breaks = c(0, 500, 1000)
  ) +
  annotate(
    "label", x = c(Inf, -Inf), y = c(-Inf, Inf),
    label = c("P02 HB" , "P02 PB"), hjust = c(1, 0), vjust = c(1, 0),
    label.padding = unit(2.25, "pt"), label.size = NA,
    fill = NA
  ) +
  guides(
    x.sec = ggh4x::guide_axis_scalebar(
      size = 50, label = "50 Mb"
    ),
    fill = gguidance::guide_colourbar_cap(
      cap_position = "upper",
      barheight = unit(5.5, "pt"),
      barwidth = unit((size - 0.1672)/2, "cm"),
      order = 2,
      title.position = "top"
    ),
    fill_new = gguidance::guide_colourbar_cap(
      cap_position = "upper", available_aes = "fill_new",
      barheight = unit(5.5, "pt"),
      barwidth = unit(size - 0.1672, "cm"),
      title = "Contacts",
      title.position = "top",
      order = 1
    )
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0),
    breaks = brks$mid,
    labels = brks$V1,
    name   = NULL
  ) +
  scale_x_continuous(
    expand = c(0, 0),
    breaks = brks$mid,
    labels = brks$V1,
    name   = NULL
  ) +
  ggh4x::force_panelsizes(
    rows = unit(size, "cm"),
    cols = unit(size, "cm")
  ) +
  theme(
    axis.text.y.left = element_text(angle = 90, hjust = 0.5),
    aspect.ratio = 1,
    legend.position = "bottom",
    legend.box = "vertical",
    legend.box.just = "left",
    legend.text = element_text(hjust = 0.5)
  )

save_svg("Fig_Translocation_Example2", g)
```

```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr6", "chr7", "chr8")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P02_HB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P02_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```

### P02

```{r}
exps <- load_experiments(sample_subset = c("P02_HB", "P02_PB"), 
                         resolution = 5e5, balancing = FALSE)
exps <- sync_indices(exps)
```


```{r}
good_chroms <- paste0("chr", c(1:22, "X"))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% c("chr14", "chr10")]
bins <- bins[order(factor(V1, good_chroms))]
bins$index <- seq_len(nrow(bins))
nbins <- nrow(bins)

mat <- matrix(0, nbins, nbins)

p1 <- exps$P02_HB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p2 <- exps$P02_PB$MAT[V1 %in% bins$V4][V2 %in% bins$V4]
p1[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]
p2[, c("V1", "V2") := list(match(V1, bins$V4), match(V2, bins$V4))]

mat[p1[, cbind(V1, V2)]] <- p1$V3
mat[p2[, cbind(V2, V1)]] <- p2$V3

df <- data.table(
  row = as.vector(row(mat)),
  col = as.vector(col(mat)),
  value = as.vector(mat)
)

brks <- bins[, .(min = min(index) - 0.5, max = max(index) + 0.5), by = "V1"]
brks[, mid := (min + max) / 2]



ggplot(df, aes(col, row, fill = value)) +
  geom_raster() +
  geom_hline(yintercept = brks$max) +
  geom_vline(xintercept = brks$max) +
  myplotdefaults::scale_fill_fire(
    limits = c(0, 300),
    oob = oob_squish
  ) +
  scale_y_continuous(
    trans  = "reverse",
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    expand = c(0, 0)
  ) +
  theme(aspect.ratio = 1)
```


## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
