---
title: "Figure HBPB TADs"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
library(GENOVA)
library(grid)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
exps <- load_experiments(resolution = 20e3, sample_subset = c("P01_HB", "P01_PB"))
exps <- sync_indices(exps)
is   <- readRDS(here("rds", "01_insulation_score.rds"))
is$exp <- sample_lut[is$exp]
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

### Functions

```{r}
makeContent.my_rast <- function(x) {
  x$children[[1]]$height <- convertWidth(x$children[[1]]$width, "cm")
  x$children[[1]]$width  <- convertWidth(x$children[[1]]$width, "cm")
  x
}
registerS3method("makeContent", "my_rast", makeContent.my_rast)

data2layer <- function(bins, exps, lim = 200, extrafacet = "IS") {
  pal <- myplotdefaults::scale_fill_fire()
  pal <- pal$palette
  
  join <- bins[, CJ(V1 = V4, V2 = V4)]
  join <- join[V2 >= V1]
  
  m <- matrix("#FFFFFF", nrow(bins), nrow(bins))
  m[lower.tri(m)] <- NA
  
  mtxs <- lapply(exps, function(exp) {
    data <- exp$MAT[join, nomatch = NULL]
    data[, c("V1", "V2") := .(match(V1, bins$V4), match(V2, bins$V4))]
    mtx <- m
    mtx[data[, cbind(V1, V2)]] <- pal(pmin(data$V3, lim) / lim)
    mtx
  })
  facet <- c(extrafacet, expnames(exps))
  
  Map(
    matrix_as_layer,
    m = mtxs,
    facet = factor(expnames(exps), facet),
    range = list(range(bins$V2, bins$V3))
  )
}

matrix_as_layer <- function(m, facet, range) {
  
  rast <- rasterGrob(
    m, width = unit(1 / sqrt(2), "npc"), height = unit(1 / sqrt(2), "npc"),
    vp = viewport(angle = 45, y = unit(0, "npc")), interpolate = FALSE
  )
  grob  <- grobTree(rast, cl = "my_rast")
  layer <- annotation_custom(
    grob, xmin = range[1], xmax = range[2]
  )
  layer$data$facet <- facet
  layer
}
```


## Aim

### Example Hi-C

```{r}
region <- list(chrom = "chr3", start = 52e6, end = 58e6)
r_name <- paste0(region$chrom, ":", number_integer(region$start), "-", 
                 number_integer(region$end))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% region$chrom]
bins <- bins[V2 >= region$start & V3 <= region$end]

colour_lim <- 800

layers <- data2layer(bins, exps, lim = colour_lim, extrafacet = "IS")

p <- ggplot(bins, aes(V2)) +
  layers +
  geom_point(
    data = bins[1,],
    aes(fill = 1, x = Inf, y = Inf), shape = NA,
    na.rm = TRUE
  ) +
  geom_text(
    data = data.frame(facet = factor(c("P01_HB" , "P01_PB"), 
                                     levels(layers$P01_HB$data$facet))),
    aes(x = -Inf, y = Inf, label = c("P01 HB", "P01 PB")),
    hjust = 0, vjust = 1
  ) +
  myplotdefaults::scale_fill_fire(
    name = "Contacts",
    limits = c(0, colour_lim), 
    guide = gguidance::guide_colourbar_cap(
      cap_position = "upper",
      barwidth = unit(5.5, "pt"),
      barheight = unit(4 - 0.1672, "cm")
    )
  ) +
  scale_x_continuous(
    expand = c(0, 0), 
    breaks = function(x) {
      oob_discard(extended_breaks()(x), x)
    },
    labels = function(x) {
      x <- number_format(scale = 1e-6)(x)
      x[1] <- paste0(x[1], "Mb")
      x
    },
    name = r_name,
    limits = c(region$start, region$end)
  ) +
  scale_y_continuous(limits = c(0, 1), guide = "none", expand = c(0, 0),
                     name = NULL) +
  ggh4x::facet_grid2(
    rows = vars(facet), axes = "x", remove_labels = "x"
  ) +
  ggh4x::force_panelsizes(
    total_height = unit(4, "cm"),
    cols = unit(6.472, "cm")
  ) +
  theme(
    axis.title.x.bottom = element_text(hjust = 0, size = 6),
    strip.text = element_blank(),
    legend.box.spacing = unit(0, "pt")
  )

save_svg("Fig_HBPB_TADs_pyramid", p)
```

### Example scores

```{r}
pats <- c("P01_HB", "P01_PB", "P02_HB", "P02_PB")

df <- is[exp %in% pats]
df <- df[chrom == region$chrom]
df <- df[start >= region$start & end <= region$end]
df[, c("pat", "type") := tstrsplit(exp, "_")]
df[, mid := (start + end) / 2]

p <- ggplot(df, aes(mid, value, colour = type, group = exp)) +
  annotate(
    "rect", xmin =54560000, xmax = 54680000, ymin = -Inf, ymax = Inf,
    fill = "grey90"
  ) +
  geom_line() +
  scale_colour_manual(
    name = NULL,
    values = colorspace::darken(sample_colours[1:2], 0.2),
    guide = ggh4x::guide_stringlegend(direction = "horizontal")
  ) +
  ggh4x::force_panelsizes(
    rows = unit(1, "cm"),
    cols = unit(6.472, "cm")
  ) +
  scale_x_continuous(
    expand = c(0, 0), 
    breaks = function(x) {
      oob_discard(extended_breaks()(x), x)
    },
    labels = function(x) {
      x <- number_format(scale = 1e-6)(x)
      x[1] <- paste0(x[1], "Mb")
      x
    },
    name = r_name,
    limits = c(region$start, region$end)
  ) +
  scale_y_continuous(
    name = "IS", breaks = c(-1, 0, 1),
    limits = ~ c(pmin(.x[1], -1), pmax(.x[2], 1))
  ) +
  theme(
    axis.title.x.bottom = element_text(hjust = 0, size = 6),
    panel.grid.major.x = thin_line,
    legend.position = c(0, 1),
    legend.justification = c(0, 1),
    legend.margin = margin(2,2,2,2)
  )

save_svg("Fig_HBPB_TADs_IS", p)
```


### Correlation

```{r}
df <- dcast.data.table(is[exp %in% pats], bin ~ exp, value.var = "value")

df <- data.table(
  x = c(df$P01_HB, df$P01_HB, df$P02_HB),
  y = c(df$P02_HB, df$P01_PB, df$P02_PB),
  group = rep(c("P01 HB vs\nP02 HB", "P01 HB vs\nP01 PB", "P02 HB vs\nP02 PB"),
              each = nrow(df))
)
df <- df[is.finite(df$x) & is.finite(df$y)]
df$group <- factor(df$group, c("P01 HB vs\nP02 HB", "P01 HB vs\nP01 PB", "P02 HB vs\nP02 PB"))

rsq <- df[, cor(x, y)^2, by = "group"]
rsq[, lab := paste0("R^2 == ", number(V1, 0.01))]

lim <- range(df$x, df$y)

p <- ggplot(df, aes(x, y)) +
  geom_abline(slope = 1, intercept = 0, colour = "grey90") +
  geom_hline(yintercept = 0, colour = "grey90") +
  geom_vline(xintercept = 0, colour = "grey90") +
  ggrastr::rasterise(
    geom_point(shape = ".", alpha = 0.1),
    dpi = 600, dev = "ragg_png"
  ) +
  geom_label(
    data = rsq,
    aes(x = Inf, y = -Inf, label = lab), 
    parse = TRUE, inherit.aes = FALSE,
    vjust = 0, hjust = 1, label.padding = unit(4.4, "pt"), 
    label.size = NA, fill = NA
  ) +
  facet_grid(~ group) +
  scale_x_continuous(limits = lim) +
  scale_y_continuous(limits = lim) +
  ggh4x::force_panelsizes(
    rows = unit(2, "cm"),
    cols = unit(2, "cm")
  ) +
  theme(
    strip.text.x.top = element_text(hjust = 0, margin = margin(b = 4.4)),
    axis.title = element_blank()
  )
p

save_svg("Fig_HBPB_TADs_correlation", p)
```

### Delta

```{r}
df <- dcast.data.table(is[exp %in% pats], chrom + start + end + bin ~ exp, value.var = "value")
df[, P01_delta := P01_PB - P01_HB]
df[, P02_delta := P02_PB - P02_HB]
df <- df[is.finite(P01_delta) & is.finite(P02_delta)]

rsq <- df[, .(cor = cor(P01_delta, P02_delta)^2)]
rsq[, lab := paste0("R^2 == ", number(cor, 0.001))]

lim <- df[, range(P01_delta, P02_delta)]
lim <- c(-1, 1) * max(abs(lim))

p <- ggplot(df, aes(P01_delta, P02_delta)) +
  geom_abline(slope = 1, intercept = 0, colour = "grey90") +
  geom_hline(yintercept = 0, colour = "grey90") +
  geom_vline(xintercept = 0, colour = "grey90") +
  ggrastr::rasterise(
    geom_point(shape = ".", alpha = 0.2),
    dpi = 600, dev = "ragg_png"
  ) +
  geom_label(
    data = rsq,
    aes(x = Inf, y = -Inf, label = lab), 
    parse = TRUE, inherit.aes = FALSE,
    vjust = 0, hjust = 1, label.padding = unit(4.4, "pt"), 
    label.size = NA, fill = NA
  ) +
  scale_x_continuous(
    limits = c(-3, 3),
    name   = "P01 ΔIS",
    labels = number_signed,
    oob    = oob_squish
  ) +
  scale_y_continuous(
    limits = c(-3, 3),
    name   = "P02 ΔIS",
    labels = number_signed,
    oob    = oob_squish
  ) +
  ggh4x::force_panelsizes(
    rows = unit(2, "cm"),
    cols = unit(2, "cm")
  )

save_svg("Fig_HBPB_delta_IS_correlation", p)
```

### More examples

#### Example Hi-C


```{r}
# exps <- c(
#   exps,
#   load_experiments(resolution = 50e3, sample_subset = c("P02_HB", "P02_PB"))
# )
pats <- c("P01_HB", "P01_PB", "P02_HB", "P02_PB")
exps <- load_experiments(resolution = 20e3, sample_subset = pats)
exps <- sync_indices(exps)
```


```{r}
region <- list(chrom = "chr6", start = 145.8e6, end = 149.5e6)
r_name <- paste0(region$chrom, ":", number_integer(region$start), "-", 
                 number_integer(region$end))

bins <- exps[[1]]$IDX
bins <- bins[V1 %in% region$chrom]
bins <- bins[V2 >= region$start & V3 <= region$end]

colour_lim <- 200

layers <- data2layer(bins, exps, lim = colour_lim)

p <- ggplot(bins, aes(V2)) +
  layers +
  geom_point(
    data = bins[1,],
    aes(fill = 1, x = Inf, y = Inf), shape = NA,
    na.rm = TRUE
  ) +
  geom_text(
    data = data.frame(facet = factor(c("P01_HB" , "P01_PB", "P02_HB", "P02_PB"), 
                                     levels(layers$P01_HB$data$facet))),
    aes(x = -Inf, y = Inf, label = c("P01 HB", "P01 PB", "P02 HB", "P02 PB")),
    hjust = 0, vjust = 1
  ) +
  myplotdefaults::scale_fill_fire(
    name = "Contacts",
    limits = c(0, colour_lim), 
    guide = gguidance::guide_colourbar_cap(
      cap_position = "upper",
      barwidth = unit(5.5, "pt"),
      barheight = unit(4 - 0.1672, "cm")
    )
  ) +
  scale_x_continuous(
    expand = c(0, 0), 
    breaks = function(x) {
      oob_discard(extended_breaks()(x), x)
    },
    labels = function(x) {
      x <- number_format(scale = 1e-6)(x)
      x[1] <- paste0(x[1], "Mb")
      x
    },
    name = r_name,
    limits = c(region$start, region$end)
  ) +
  scale_y_continuous(limits = c(0, 1), guide = "none", expand = c(0, 0),
                     name = NULL) +
  ggh4x::facet_grid2(
    rows = vars(facet), axes = "x", remove_labels = "x"
  ) +
  ggh4x::force_panelsizes(
    total_height = unit(4, "cm"),
    cols = unit(6.472, "cm")
  ) +
  theme(
    axis.title.x.bottom = element_text(hjust = 0, size = 6),
    strip.text = element_blank(),
    legend.box.spacing = unit(0, "pt")
  )
save_svg("Fig_HBPB_TADs_pyramid2", p)
```
### Example scores

```{r}
pats <- c("P01_HB", "P01_PB", "P02_HB", "P02_PB")

df <- is[exp %in% pats]
df <- df[chrom == region$chrom]
df <- df[start >= region$start & end <= region$end]
df[, c("pat", "type") := tstrsplit(exp, "_")]
df[, mid := (start + end) / 2]

p <- ggplot(df, aes(mid, value, colour = type, group = exp)) +
  annotate(
    "rect", xmin =54560000, xmax = 54680000, ymin = -Inf, ymax = Inf,
    fill = "grey90"
  ) +
  geom_line() +
  scale_colour_manual(
    name = NULL,
    values = colorspace::darken(sample_colours[1:2], 0.2),
    guide = ggh4x::guide_stringlegend(direction = "horizontal")
  ) +
  ggh4x::force_panelsizes(
    rows = unit(1, "cm"),
    cols = unit(6.472, "cm")
  ) +
  scale_x_continuous(
    expand = c(0, 0), 
    breaks = function(x) {
      oob_discard(extended_breaks()(x), x)
    },
    labels = function(x) {
      x <- number_format(scale = 1e-6)(x)
      x[1] <- paste0(x[1], "Mb")
      x
    },
    name = r_name,
    limits = c(region$start, region$end)
  ) +
  scale_y_continuous(
    name = "IS", breaks = c(-1, 0, 1),
    limits = ~ c(pmin(.x[1], -1), pmax(.x[2], 1))
  ) +
  theme(
    axis.title.x.bottom = element_text(hjust = 0, size = 6),
    panel.grid.major.x = thin_line,
    legend.position = c(0, 1),
    legend.justification = c(0, 1),
    legend.margin = margin(2,2,2,2)
  )

save_svg("Fig_HBPB_TADs_IS2", p)
```




## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
