---
title: "Figure CNV aggregate"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
library(GenomicRanges)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
cnvs <- data.table::fread(here("processed_data", "cnvs", "res_2e+06.tsv"))
centros <- readRDS(here("references", "centromeres.rds"))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

## Wrangling

```{r}
cnv_gr <- cnvs[, GRanges(chrom, IRanges(start, end))]
snames <- colnames(cnvs)[-c(1:4)]
olap   <- overlapsAny(cnv_gr, centros)
setDF(cnvs)
cnvs[olap, snames] <- NA
setDT(cnvs)
```


```{r}
stype <- paste0(sample_type, ", n = ", c(2, 5, 1, 3, 10))
stype <- setNames(stype, names(sample_type))

df <- melt.data.table(cnvs, id.vars = "bin", measure.vars = patterns("^P"))
df$variable <- sample_lut[as.character(df$variable)]
df[, c("pat", "type") := tstrsplit(variable, "_")]
df$type <- factor(df$type, names(stype), stype)
df <- df[!df$variable %in% c("P14_??", "P12_BR")]
df[, c("gain", "loss") := list(value > log2(1.25), value < log2(0.75))]
df <- df[, .(gain = sum(gain), loss = sum(loss), n = length(unique(variable))),
         by = c("bin", "type")]

chroms <- cnvs[, .(min = min(bin), max = max(bin)), by = "chrom"]
chroms[, mid := (min + max) / 2]
chroms$chrom[-1] <- gsub("chr", "", chroms$chrom[-1])
chroms[chrom %in% c("17", "19", "21"), chrom := paste0("\n", chrom)]

breaks <- as.vector(rbind(chroms$min, chroms$max))
breaks <- breaks[-c(1, length(breaks))]
breaks <- vapply(
  split(breaks, rep(seq_along(breaks), each = 2)[seq_along(breaks)]),
  mean, numeric(1)
)

tab <- colnames(cnvs)[-c(1:4)]
tab <- tstrsplit(sample_lut[tab], "_")[[2]]
tab <- table(tab)
tab <- setNames(as.vector(tab), names(tab))
```

## Plotting

```{r}
df <- df[!is.na(type) & type != "Breast Recurrent, n = 1"]

p <- ggplot(df, aes(bin)) +
  geom_rect(
    data = chroms[seq_len(nrow(chroms)) %% 2 == 0],
    aes(ymin = -Inf, ymax = Inf, xmin = min, xmax = max),
    inherit.aes = FALSE, alpha = 0.5, colour = "grey90", fill = "grey90"
  ) +
  geom_area(
    aes(y = gain / n, fill = "Gain", !!!dark_outline),
    position = "identity", stat = "identity", outline.type = "upper",
    alpha = 0.5
  ) +
  geom_area(
    aes(y = loss / n, fill ="Loss", !!!dark_outline),
    position = "identity", stat = "identity", outline.type = "upper",
    alpha = 0.5
  ) +
  facet_wrap(
    vars(type), ncol = 1,
    scales = "free_y"
  ) +
  scale_x_continuous(
    breaks = chroms$mid,
    labels = chroms$chrom,
    expand = c(0, 0),
    name = NULL
  ) +
  scale_y_continuous(
    expand = c(0, 0), breaks = c(0, 0.5, 1),
    name = "Fraction of samples",
    limits = c(0, 1)
  ) +
  scale_fill_manual(
    values = c("#ff5c49", "#009bef"),
    guide = ggh4x::guide_stringlegend(), name = NULL
  ) +
  # scale_y_discrete(
  #   expand = c(0, 0), name = NULL,
  #   limits = rev
  # ) +
  # scale_fill_gradientn(
  #   colours  = div_colours,
  #   rescaler = ~ rescale_mid(.x, mid = 0),
  #   name     = expression("Log"[2]*" Ratio"),
  #   guide    = hcolourbar(),
  #   limits   = ~ c(-1, 1) * .x[2]
  # ) +
  ggh4x::force_panelsizes(
    total_height = unit(6 * 2 / (1 + sqrt(5)), "cm"),
    total_width = unit(6, "cm")
    # rows = unit(c(3) * 8, "pt"),
    # col = unit(7.5, "cm")
  ) +
  theme(
    axis.ticks.x = element_blank(),
    strip.text = element_text(hjust = 0, size = 8,
                              margin = margin(t = 4.4, b = 4.4)),
    legend.position = c(1, 1),
    legend.justification = c(1, 1),
    panel.spacing.y = unit(0, "pt")
  )

save_svg("Fig_XX_CNV_aggregate", width = 80, height = 120)
```


## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
