---
title: "Figure PESCAn Quantification"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
quant <- readRDS(here("rds", "01_PESCAn_quantification_our_data.rds"))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

## Wrangling

```{r}
neg_pats <- c("P13", "P14", "P15")
# Modification after pathology updates
neg_pats <- c(neg_pats, c("P07", "P11"))

n_bootstrap <- 1000

mtx <- dcast.data.table(
  quant$per_interaction,
  feature_id ~ sample, fill = 0,
  value.var = "difference"
)
mtx <- as.matrix(mtx[, -1, with = FALSE])
n <- nrow(mtx)

set.seed(20230707)
bootstrap <- vapply(
  seq_len(n_bootstrap),
  function(i) colMeans(mtx[sample(n, replace = TRUE), ]),
  numeric(ncol(mtx))
)
names(dimnames(bootstrap)) <- c("sample", "iter")

df <- as.data.table(reshape2::melt(bootstrap))
df$sample <- sample_lut[as.character(df$sample)]
df[, c("pat", "type") := tstrsplit(sample, "_")]
df[, status := ifelse(pat %in% neg_pats, "ERα\u2212", "ERα+")]

neg <- df[pat %in% neg_pats, mean(value)]
```

## Plot

```{r}
df$y <- factor(
  paste0(df$pat, "&", df$status),
  c("P01&ERα+", "P02&ERα+", "P03&ERα+", "P04&ERα+", "P05&ERα+", "P06&ERα+", 
    "P08&ERα+", "P09&ERα+", "P10&ERα+", "P12&ERα+", "P07&ERα−", "P11&ERα−",
    "P13&ERα−", "P14&ERα−", "P15&ERα−")
)

p <- ggplot(df, aes(value, y, fill = type)) +
  geom_vline(xintercept = neg, linetype = "dashed") +
  ggdist::stat_halfeye(
    aes(alpha = after_stat(ggdist::cut_cdf_qi(cdf, .width = c(1, .95, .66)))),
    geom = "slab"
  ) +
  scale_alpha_manual(
    values = c(1, 0.5, 0.25),
    guide  = "none"
  ) +
  scale_fill_manual(
    values = sample_colours,
    limits = setdiff(names(sample_colours), "BR"),
    labels = sample_type,
    na.value = NA,
    guide = ggh4x::guide_stringlegend(face = "bold"),
    name = NULL
  ) +
  scale_x_continuous(
    limits = c(0, NA),
    expand = c(0, 0, 0.05, 0),
    breaks = breaks_width(0.1),
    name = "Foreground - Background\n(Bootstrapped)"
  ) +
  scale_y_discrete(
    expand = c(0, 0),
    limits = rev,
    name = NULL
  ) +
  guides(
    x.sec = ggh4x::guide_axis_manual(breaks = neg, labels = "Mean ER-"),
    y = ggh4x::guide_axis_nested(delim = "&")
  ) +
  ggh4x::force_panelsizes(
    rows = unit(15 * 8, "pt"),
    cols =  unit(4, "cm") + unit(5.5, "pt")
  ) +
  theme(
    axis.text.y.left = element_text(vjust = 0, margin = margin(5,5,5,5)),
    axis.line.x.top  = element_blank(),
    axis.ticks.x.top = element_blank(),
    legend.position = c(0, 1),
    legend.justification = c(0, 1),
    legend.margin = margin(0,0,0,2.25),
    panel.grid.major = thin_line,
    panel.grid.minor.x = thin_line
  )

save_svg("Fig_PESCAn_quantification", p)
```


## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
