---
title: "Figure Similarities"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
library(GENOVA)
library(GenomicRanges)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
tads <- readRDS(here("rds", "01_TADs.rds"))
tads$exp <- sample_lut[tads$exp]

dissim <- list.files(here("temp"), full.names = TRUE)
dissim <- rbindlist(lapply(dissim, fread))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

### TAD similarities

```{r}
borders <- with(tads, GRanges(
  seqnames = c(chrom, chrom),
  IRanges(c(start, end), width = 1),
  exp = c(exp, exp)
))

wide_borders <- reduce(resize(borders, 3 * 20e3, fix = "center"))
binary <- vapply(
  split(borders, borders$exp),
  overlapsAny, logical(length(wide_borders)), query = wide_borders
)

# Calculate Jaccard index
n_tads   <- colSums(binary)
intersec <- crossprod(binary)
union    <- outer(n_tads, n_tads, "+") - intersec
jac <- intersec/union
diag(jac) <- NA
jac[upper.tri(jac)] <- NA

# Plot
df <- as.data.table(reshape2::melt(jac))
df <- df[!is.na(value)]
df[, c("left_pat",  "left_type")  := tstrsplit(Var1, "_")]
df[, c("right_pat", "right_type") := tstrsplit(Var2, "_")]
df[, same_type := left_type == right_type]
df[, same_pat  := left_pat  == right_pat]

same_type <- df[same_type == TRUE]
same_type <- same_type[!is.na(value)]

types <- c("HB", "PB", "LM", "PE")

same_pat <- df[same_pat == TRUE]
same_pat <- same_pat[left_type %in% types & right_type %in% types]
same_pat[, left_idx  := match(left_type,  rev(types))]
same_pat[, right_idx := match(right_type, rev(types))]
same_pat <- same_pat[abs(left_idx - right_idx) == 1]
same_pat[, y := (left_idx + right_idx) / 2]

col <- aes(colour = after_scale(colorspace::darken(fill, 0.2)))

p <- ggplot(same_type, aes(value, left_type, fill = left_type)) +
  ggbeeswarm::geom_beeswarm(
    side = 1, size = 1, cex = 2,
    col, shape = 21
  ) +
  geom_boxplot(
    outlier.shape = NA,
    aes(ymax = after_scale(y), !!!col),
    position = position_nudge(y = -0.2),
    width = 0.4
  ) +
  geom_errorbar(
    stat = "boxplot",
    aes(ymax = after_scale(y), !!!col),
    position = position_nudge(y = -0.2),
    width = 0.25
  ) +
  scale_y_discrete(
    limits = rev(types),
    labels = c("Pleural Effusion", "Liver Metastasis", "Primary Breast",
               "Healthy Breast"),
    name = NULL
  ) +
  scale_x_continuous(
    name   = "Jaccard Index"
  ) +
  scale_fill_manual(
    values = sample_colours, guide = "none"
  ) +
  ggh4x::force_panelsizes(
    rows = unit(2, "cm"),
    cols = unit(1 + sqrt(5), "cm")
  ) +
  theme(
    panel.grid.major.x = thin_line,
    axis.text.y.left = element_text(hjust = 0)
  )

save_svg("Fig_Similarity_Borders")
```

### Compartment similarities

```{r}
df <- dissim[!is.na(score)]
df <- df[, .(avg = sum(score * width) / sum(width)), by = c("V1", "V2")]
df[, c("left_pat",  "left_type")  := tstrsplit(V1, "_")]
df[, c("right_pat", "right_type") := tstrsplit(V2, "_")]
df[, same_type := left_type == right_type]
df[, same_pat  := left_pat  == right_pat]

sub <- df[same_type == TRUE]

ggplot(sub, aes(avg, left_type, fill = left_type)) +
  ggbeeswarm::geom_beeswarm(
    side = 1, size = 1, cex = 2,
    col, shape = 21
  ) +
  geom_boxplot(
    outlier.shape = NA,
    aes(ymax = after_scale(y), !!!col),
    position = position_nudge(y = -0.2),
    width = 0.4
  ) +
  geom_errorbar(
    stat = "boxplot",
    aes(ymax = after_scale(y), !!!col),
    position = position_nudge(y = -0.2),
    width = 0.25
  ) +
  scale_y_discrete(
    limits = rev(types),
    labels = c("Pleural Effusion", "Liver Metastasis", "Primary Breast",
               "Healthy Breast"),
    name = NULL
  ) +
  scale_x_continuous(
    name   = "Weighted ΔR"
  ) +
  scale_fill_manual(
    values = sample_colours, guide = "none"
  ) +
  ggh4x::force_panelsizes(
    rows = unit(2, "cm"),
    cols = unit(1 + sqrt(5), "cm")
  ) +
  theme(
    panel.grid.major.x = thin_line,
    axis.text.y.left = element_text(hjust = 0)
  )
```



## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
