---
title: "Saddle / CS strength"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
library(GENOVA)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
sad <- readRDS(here("rds", "01_saddle.rds"))
saddle <- sad$saddle
saddle$exp <- sample_lut[saddle$exp]

cs <- readRDS(here("rds", "01_compartment_scores.rds"))

dis <- readRDS(here("rds", "01_compartment_dissimilarity.rds"))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

## Saddle

```{r}
df <- saddle[exp %in% c("P15_PE", "P12_PE")]
df <- df[!is.na(mean) & !is.na(q1) & !is.na(q2)]
df <- rbind(df, df[, .(exp = exp, chr = chr, q1 = q2, q2 = q1, mean = mean)])
df <- df[, .(mean = mean(mean)), by = c("exp", "q1", "q2")]
df$exp <- gsub("_", " ", df$exp)


p <- ggplot(df, aes(q1, q2, fill = log2(mean))) +
  geom_raster() +
  scale_fill_gradientn(
    colours = div_colours,
    rescaler = ~ rescale_mid(.x, mid = 0),
    breaks = breaks_width(1),
    labels = number_signed,
    name   = expression(atop("Log"[2]," Observed / Expected")),
    guide  = guide_colourbar(
      title.position = "top",
      barheight = unit(5.5, "pt"),
      barwidth  = unit(1.80811413204834, "cm")
    )
  ) +
  scale_x_continuous(
    expand = c(0, 0),
    breaks = force,
    labels = c("B", "A"),
    name   = NULL
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = force,
    labels = c("B", "A"),
    name   = NULL
  ) +
  facet_wrap(~ exp, ncol = 1) +
  ggh4x::force_panelsizes(
    total_height = unit(4, "cm"),
    cols = unit(1.80811413204834, "cm"), respect = TRUE
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(hjust = 0),
    strip.text.x = element_text(hjust = 0, margin = margin(t = 2, b = 2)),
    panel.spacing.y = unit(0, "pt")
  )

save_svg("Fig_Compartments_Saddle", p)
```

## Strength

```{r}
quant <- quantify(sad)
quant <- quant[!duplicated(data.frame(exp, chr))]
quant[, exp := sample_lut[as.character(exp)]]

boot <- function(x, n = 1000) {
  colMeans(matrix(sample(x, n, replace = TRUE), length(x), n))
}

quant <- quant[, .(value = boot(strength)), by = "exp"]
quant[, c("pat", "type") := tstrsplit(exp, "_")]

p <- ggplot(quant, aes(value, pat, fill = type)) +
  ggdist::stat_halfeye(
    aes(alpha = after_stat(ggdist::cut_cdf_qi(cdf, .width = c(1, .95, .66)))),
    geom = "slab"
  ) +
  scale_alpha_manual(
    values = c(1, 0.5, 0.25),
    guide = "none"
  ) +
  scale_fill_manual(
    values = sample_colours,
    limits = setdiff(names(sample_colours), "BR"),
    labels = sample_type,
    na.value = NA,
    guide = ggh4x::guide_stringlegend(face = "bold"),
    name = NULL
  ) +
  scale_x_continuous(
    limits = c(1, NA),
    breaks = breaks_width(0.5),
    name   = "Compartment Strength\n(Bootstrapped)"
  ) +
  scale_y_discrete(
    expand = c(0, 0),
    limits = rev,
    name   = NULL
  ) +
  ggh4x::force_panelsizes(
    rows = unit(15 * 8, "pt"),
    cols = unit(4.5, "cm")
  ) +
  theme(
    axis.text.y.left = element_text(vjust = 0, margin = margin(5,5,5,5)),
    panel.grid.major = thin_line
  )

save_svg("Fig_Compartment_Strength", p)
```

## Similarity

```{r}
dissim <- dis[, .(avg = sum(score * width) / sum(width)), by = c("V1", "V2")]
dissim[, c("V1", "V2") := .(sample_lut[V1], sample_lut[V2])]
dissim[, c("left_pat",  "left_type")  := tstrsplit(V1, "_")]
dissim[, c("right_pat", "right_type") := tstrsplit(V2, "_")]
dissim[, same_type := left_type == right_type]

p <- ggplot(dissim[same_type == TRUE]) +
  aes(avg, left_type, fill = left_type, !!!dark_outline) +
  ggbeeswarm::geom_beeswarm(
    side = 1, size = 1, cex = 2,
    shape = 21
  ) +
  geom_boxplot(
    outlier.shape = NA,
    aes(ymax = after_scale(y)),
    position = position_nudge(y = -0.2),
    width = 0.4
  ) +
  geom_errorbar(
    stat = "boxplot",
    aes(ymax = after_scale(y)),
    position = position_nudge(y = -0.2),
    width = 0.25
  ) +
  scale_y_discrete(
    limits = c("PE", "LM", "PB", "HB"),
    labels = c("Pleural Effusion", "Liver Metastasis", 
               "Primary Breast", "Healthy Breast"),
    name = NULL
  ) +
  scale_x_continuous(
    name   = "Weighted |ΔR|",
    breaks = breaks_width(0.1)
  ) +
  scale_fill_manual(
    values = sample_colours, guide = "none"
  ) +
  ggh4x::force_panelsizes(
    rows = unit(2, "cm"),
    cols = unit(4, "cm")
  ) +
  theme(
    panel.grid.major.x = thin_line,
    axis.text.y.left = element_text(hjust = 0)
  )

save_svg("Fig_Compartment_Dissimilarity", p)
```


```{r}



df <- data.frame(x = rnorm(10000))

ggplot(df, aes(x)) +
    ggdist::stat_halfeye(
    aes(alpha = after_stat(ggdist::cut_cdf_qi(cdf, .width = c(1, .95, .66)))),
    geom = "slab"
  )
  


ggplot() +
  stat_function(
    geom = "area",
    fun = dnorm,
    xlim = qnorm(c(0.17, 0.83)),
    fill = "black"
  ) +
  stat_function(
    geom = "area",
    fun = dnorm,
    xlim = qnorm(c(0.025, 0.975)),
    fill = "black", alpha = 0.5
  ) +
  stat_function(
    geom = "area",
    fun = dnorm,
    xlim = qnorm(c(1e-3, 1 - 1e-3)),
    fill = "black", alpha = 0.25
  )


```



## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
