---
title: "Figure Sample Overview"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

```{r}
df <- data.table(
  sample = sample_lut
)
df[, c("pat", "type") := tstrsplit(sample, "_")]
df[, status := "+"]
df[pat %in% c("P13", "P14", "P15"), status := "\u2212"]

p <- ggplot(df, aes(pat, type)) +
  geom_tile(
    data = expand.grid(pat = unique(df$pat), type = unique(df$type)),
    fill = "white", colour = "grey90",
    na.rm = TRUE, linewidth = 0.5
  ) +
  geom_tile(
    aes(fill = type,
        colour = after_scale(colorspace::darken(fill, 0.2))),
    na.rm = TRUE,
    linewidth = 0.5
  ) +
  geom_text(
    aes(label = status)
  ) +
  scale_y_discrete(
    limits = rev(names(sample_type)[-3]),
    labels = rev(sample_type[-3]),
    expand = c(0, 0),
    name   = NULL
  ) +
  scale_fill_manual(
    limits = rev(names(sample_type)[-3]),
    values = rev(sample_colours[names(sample_type)[-3]]),
    guide  = "none"
  ) +
  scale_x_discrete(
    expand = c(0, 0),
    name   = NULL
  ) +
  coord_fixed(clip = "off") +
  ggh4x::force_panelsizes(
    rows = unit(4 * 12, "pt"),
    cols = unit(15 * 12, "pt")
  ) +
  theme(
    axis.text.y.left = element_text(hjust = 0)
  )

save_svg("Fig_Sample_Overview", p)
```


## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
