---
title: "Untitled"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
data <- fread(here("references", "TAD_border_cistrome_stats.tsv"))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

```{r}
spec <- data[fdr < 1e-3 & coef < 0, ][, .(n_spec = .N), by = "Factor"]
gen  <- data[fdr < 1e-3 & coef > 0, ][, .(n_gen = .N), by = "Factor"]
all  <- data[, .(n_all = .N), by = "Factor"]

whole <- spec[all, on = "Factor"][is.na(n_spec), n_spec := 0]
whole <- gen[whole, on = "Factor"][is.na(n_gen), n_gen := 0]

spec <- whole[n_spec > 2]
gen  <- whole[n_gen > 2]
```

```{r}
df <- data.frame(
  factor = c(spec$Factor, gen$Factor),
  n = c(spec$n_spec, gen$n_gen),
  total = c(spec$n_all, gen$n_all),
  border = rep(c("Specific", "Invariant"), c(nrow(spec), nrow(gen)))
)
df <- df[order(df$border, df$n), ]
w <- 2 / (1 + sqrt(5))

p <- ggplot(df, aes(y = factor)) +
  geom_col(aes(x = total, fill = "Total"), width = w) +
  geom_col(aes(x = n, fill = border), width = w^2) +
  geom_text(
    data = data.frame(
      x = max(df$total), y = c(10, 11, which.max(df$total) - 0.5),
      label = c("Enriched in invariant borders", "Enriched in specific borders", "Considered in total"),
      col = c("Invariant", "Specific", "Total")
    ),
    aes(x = x, y = y, label = label, colour = stage(col, after_scale = colorspace::darken(colour, 0.2))),
    hjust = 1, fontface = "bold"
  ) +
  geom_hline(yintercept = 10.5, linetype = 2) +
  scale_fill_manual(
    aesthetics = c("colour", "fill"),
    name = "Datasets:",
    values = c("orchid", "orange", "grey90"),
    limits = c("Specific", "Invariant", "Total"),
    labels = c(
      "Enriched in specific borders",
      "Enriched in invariant borders",
      "Considered in total"
    ),
    guide = "none"
  ) +
  scale_y_discrete(
    limits = df$factor, name = "ChIP target"
  ) +
  scale_x_continuous(
    name = "Number of datasets",
    expand = c(0, 0, 0.05, 0)
  ) +
  scale_linetype_manual(values = "dotted") +
  theme(
    aspect.ratio = 1/w
  ) +
  ggh4x::force_panelsizes(
    rows = unit(nrow(df) * 10, "pt"),
    cols = unit(nrow(df) * 10 / w, "pt")
  )

save_svg("Fig_Cistrome", p)
```



## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
