---
title: "Figure PESCAn Examples"
author: 
  - name: "Teun van den Brand"
    email: "t.vd.brand@nki.nl"
    affiliation: "Netherlands Cancer Institute"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output: 
  html_document:
    theme: united
    highlight: pygments
    fig_caption: yes
    code_folding: hide
    df_print: kable
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
bibliography: /DATA/users/t.vd.brand/bibliography/articles.bibtex
knit: |
  # Redirect output to HTML folder
  (function(inputFile, encoding) {
    outputFile <- gsub("Rmd$", "html", basename(inputFile))
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = here::here("html", outputFile)
    )
  })
---

## Setup {.tabset}

<!-- little HTML script to do indentation of the table of contents -->
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{css, echo = FALSE}
div.sourceCode {
  overflow-x: hidden;
}
```

### Load packages

```{r stfu, include = FALSE}
# No, I do *not* want your start-up messages, thank you very much
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```


```{r load_packages}
library(ggplot2)
library(scales)
library(here)
library(data.table)
source(here("rscripts", "project_functions.R"))
```

### Load data

```{r load_data}
pescan <- readRDS(here("rds", "01_PESCAn_summaries_our_data.rds"))
```

### Setup Aesthetics

```{r setup_aes}
set_figure_theme()
```

## Aim

## Wrangling

```{r}
examples <- c("P15_PE", "P06_PE")
dimnames(pescan$obsexp)[[3]] <- sample_lut[dimnames(pescan$obsexp)[[3]]]

df <- pescan$obsexp[, , examples]
names(dimnames(df)) <- c("x", "y", "sample")
df <- reshape2::melt(df)
levels(df$sample) <- c("P15 PE, ER\u2212", "P06 PE, ER+")
```

## Plot

```{r}
p <- ggplot(df, aes(x, y, fill = value)) +
  geom_raster() +
  scale_fill_gradientn(
    colours = div_colours,
    rescaler = ~ rescale_mid(.x, mid = 1),
    name = "Observed / Expected",
    breaks = breaks_width(0.2),
    guide = hcolourbar(barwidth = unit(4, "cm") + unit(5.5, "pt"))
  ) +
  scale_x_continuous(
    name   = NULL,
    breaks = c(-2.5, 0, 2.5) * 1e5,
    labels = c("\u2212250kb", "0", "+250kb"),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name   = NULL,
    breaks = c(-2.5, 0, 2.5) * 1e5,
    labels = c("+250kb", "0", "\u2212250kb"),
    expand = c(0, 0)
  ) +
  facet_wrap(vars(sample)) +
  ggh4x::force_panelsizes(rows = unit(2, "cm"), cols = unit(2, "cm")) +
  theme(
    axis.text.y.left = element_text(angle = 90, hjust = 0.5),
    legend.position = "bottom",
    legend.margin = margin(),
    legend.box.spacing = unit(2.25, "pt"),
    strip.text = element_text(hjust = 0, margin = margin(0, 0, 4.4, 0))
  )

save_svg("Fig_PESCAn_examples", p)
```


## References

<div id="refs"></div>

## Session Info

```{r session_info, include=TRUE, echo=FALSE, results = "asis"}
pkgs <- loadedNamespaces()
libTvdB::format_sessioninfo_html(pkgs)
```
